encoding: utf-8

plugins:
  - jekyll-regex-replace
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

title: ᠠᠷᠪᠢᠰ
description: Миний аялал болон номын сангийн дээжээс түүвэрлэн үндэстэн, ястны зан заншил, соёлын өв, урлаг, түүх, нийгмийн үнэт зүйлийг эрэлхийлж тунгаан бичих орон зай
url: "http://arvis.xyz"
tagline: Соёл урлаг болон уран зохиолын мөн чанарыг эрэлхийлэх нь
logo: "/static/img/logo.jpg"
keywords: Хүн,Соёл,Түүх,Нийгэм,Урлаг,Аялал,Уран зохиол,Ном
author: ᠠᠷᠪᠢᠰ
footerText: '᠒᠐᠒᠔ ᠠᠷᠪᠢᠰ'

permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

domainUrl: 'http://arvis.xyz'
baseurl: ''

google_analytics: "G-C80FJYNJFK"

extClickEffect: true

extAdsense: false

extMath: false

extCount: false
